name: Docs

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        run: ./yarn-monorepo-install
      - name: Create the docs and pages directory locally in CI
        run: yarn build && yarn build:docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: pages
      - name: Deploy Readme docs
        uses: readmeio/rdme@7.5.0
        with:
          rdme: docs ./docs --version=v2.0 --key=${{ secrets.README_API_KEY }}
