name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        uses: ./.github/actions/yarn-monorepo-install
      - name: Build docs
        run: yarn build && yarn build:docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs-out
